// LOCAL HOST
### Get all accounts
GET http://localhost:3002/accounts

### Create account
POST http://localhost:3002/accounts HTTP/1.1
Content-Type: application/json

{
    "name": "Dorestan Junior",
    "email": "dorestan@gmail.com",
    "accountType": "Saving",
    "initialDeposit": "500"
}

### PUT account
PUT http://localhost:3002/accounts/67e5f05b891412a5dc0cee95 HTTP/1.1
Content-Type: application/json

{
    "name": "Dorestan Junior",
    "email": "dorestan@gmail.com",
    "accountType": "Saving",
    "initialDeposit": "1750"
}

### Delete account
DELETE http://localhost:3002/accounts/67e5e91ab8e94223aeb8d0a9 HTTP/1.1
